name: checks
on: [push, pull_request]
jobs:
  checks:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: ['7.3', '7.4']
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php}}
          tools: composer
      - name: Install CMSimple_XH
        run: |
          curl -fsSL -o CMSimple_XH-1.7.5.zip https://github.com/cmsimple-xh/cmsimple-xh/releases/download/1.7.5/CMSimple_XH-1.7.5.zip
          unzip -q CMSimple_XH-1.7.5.zip
      - name: Checkout Twocents_XH
        uses: actions/checkout@v3
        with:
          path: 'cmsimplexh/plugins/twocents'
      - name: composer install
        run: cd cmsimplexh/plugins/twocents && composer install
      - name: phing sniff
        run: cd cmsimplexh/plugins/twocents && PATH=vendor/bin:$PATH phing sniff
      - name: phing mess
        run: cd cmsimplexh/plugins/twocents && PATH=vendor/bin:$PATH phing mess
      - name: phing unit-tests
        run: cd cmsimplexh/plugins/twocents && PATH=vendor/bin:$PATH phing unit-tests
